### ISSUE TITLE
如何将一个caffemodel分解为三个？

### ISSUE THREAD

**Issue by MirrorYuChen** [HandsomeHans/PCN-ncnn#5]
非常感谢大佬开源的ncnn版PCN模型，有一个问题想请教一下，我看到原始的PCN模型为三个prototxt文件和一个caffemodel文件，请问一下大佬是如何分离模型的，谢谢~

**Comment by HansRen1024** [comment]
@MirrorYuChen 用那一个caffemodel分别和三个prototxt做 caffe 到ncnn框架的转换就好了。转换工具会根据prototxt提供的网络结构自己去找到对应的参数。

**Comment by MirrorYuChen** [comment]
哦哦，好的，谢谢大佬~
